version: '3.9'
services:
  server:
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.port=3001"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-server.rule=Host(`${APP_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-server.middlewares=${COMPOSE_PROJECT_NAME}-server-stripprefix"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-server-stripprefix.stripprefix.prefixes=/api"
      #  - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-server.tls.certresolver=letsencrypt"

  client:
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.port=5173"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-client.rule=Host(`${APP_HOST}`)"
      #  - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-client.tls.certresolver=letsencrypt"

  mongo-express:
    image: mongo-express
    networks:
      - internal
      - traefik
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_SITE_BASEURL: /express
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.port=8081"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-express.rule=Host(`${APP_HOST}`) && PathPrefix(`/express`)"
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-express.tls.certresolver=letsencrypt"

  traefik:
    image: traefik:v2.10
    restart: on-failure
    environment:
      - TRAEFIK_PROVIDERS_FILE_DIRECTORY=/etc/traefik
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_API=true
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_NETWORK=traefik
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=false"
