version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    restart: ${RESTART_POLYCY}
    environment:
      - NODE_ENV
    depends_on:
      - server
    volumes:
      - ./client:/app
    networks:
      - traefik
      - internal
  
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    restart: ${RESTART_POLYCY}
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
    networks:
      - traefik
      - internal

  mongodb:
    image: mongo
    restart: ${RESTART_POLYCY}
    command: "${DB_PARAMS}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT:-27017}:27017
    volumes:
      - ./docker/volumes/mongodb:/data/db
      - ./docker/mongo:/docker-entrypoint-initdb.d
    labels:
      - "traefik.enable=false"
    networks:
      - internal


networks:
  internal:
    driver: bridge
  traefik:
    external: true
